### ISSUE TITLE
Feature Request: Follow System Theme

### ISSUE THREAD

**Issue by adhdandy** [FenPhoenix/AngelLoader#122]
Can we have an option to make the application theme match the system theme?
I like to use light mode during the day and dark mode at night and it would be nice if AngelLoader could switch themes automatically based on my App-Mode settings.

**Comment by FenPhoenix** [comment]
Probably. The actual detection of a theme mode change is something I'm having to research as it's weirdly not simple but I _think_ it should be possible?

**Comment by FenPhoenix** [comment]
Added.
