### ISSUE TITLE
Prevented from loading any game after OS forced logout

### ISSUE THREAD

**Issue by ursasenior** [FenPhoenix/AngelLoader#134]
Currently facing an issue where i'm unable to load any game or load/unload any FM through AngelLoader, being prompted with the modal "One or more supported games are already running. Please exit them first".

None of the supported games are running, so I suspect AngelLoader might be permanently blocked by some lockfile that was not cleaned up during logout. 

`1.9.6 build x64`

**Preceding steps:**
- Was playing a T2 FM when the Thief 2 application hung while alt-tabbed
- Application wouldn't even respond to taskkill, so I chose to force logoff windows instead
- Upon reopening AngelLoader the behaviour described above is persistent

**Comment by FenPhoenix** [comment]
Are you sure Thief 2 isn't still running (check the Task Manager -> Details tab)? AL simply checks the list of running processes to see if a game is running. If Thief 2 hung and then you logged off and on again, it may very well still be running but without a window, or a hidden window, or who knows what weird state.

**Comment by ursasenior** [comment]
Ok excellent idea. I had booted the PC up today and encountered the issue again before reading this, so I performed a full shutdown (holding shift) instead of allowing Windows to 'soft shutdown' into hibernation mode and upon restarting the application works as expected.
