### ISSUE TITLE
AngelLoader.Common.GlobalCatOrTag appearing in tags list

### ISSUE THREAD

**Issue by codasugech** [FenPhoenix/AngelLoader#33]
I've stumbled across a small bug:
* Add a new namespace and tag to an FM, for instance, ``bug:yes``
* Delete this new tag
* Press ``Add from list``

Doing so will cause the text ``AngelLoader.Common.GlobalCatOrTag`` to fill this position in the tags list instead of being removed.

**Comment by FenPhoenix** [comment]
Thanks for catching this! It was a simple fix.
