### ISSUE TITLE
Steam Support

### ISSUE THREAD

**Issue by BogdanAlexandru** [FenPhoenix/AngelLoader#44]
AngelLoader already works fine with the steam version of Thief 2 (the only one I tried, I expect T1 and DS to work fine too), the only issue is it bypasses Steam itself when running the .exe

Would be great to add support for launching the game through Steam so one gets the Steam overlay, screenshots and playtime functionality while in FMs.

I could attempt to add this myself and file a PR if you think it's something you'd like added now and see a way it could be integrated in the GUI (a **Use Steam** checkbox?)

I'm guessing the best bet would be to use `steam.exe -applaunch <appID> [launch parameters]` in the backend.

**Comment by FenPhoenix** [comment]
I'm on it. Thanks for the suggestion.

**Comment by FenPhoenix** [comment]
@BogdanAlexandru Would you mind testing this out for me? I don't own any of the Thief games on Steam. The new version does at least open Steam and bring me to the games' store page, so I'm hoping it will launch the games if they exist in the library.

http://fenphoenix.com/apps/AngelLoader/test_versions/AngelLoader_v1.1.5_Steam_test1.zip

**Comment by BogdanAlexandru** [comment]
Thanks for the build, if I add the steam.exe to the options menu the game gets launched through steam but the fan mission doesn't seem to be applied, it launches the original game even though I ask it to launch the FM.

**Comment by FenPhoenix** [comment]
Alright, looking into it.

**Comment by FenPhoenix** [comment]
@BogdanAlexandru Okay, looks like Steam doesn't support passing the actual game's command line params with -applaunch, only internal ones. So I switched to a different method. Try this one:

http://fenphoenix.com/apps/AngelLoader/test_versions/AngelLoader_v1.1.5_Steam_test2.zip

**Comment by BogdanAlexandru** [comment]
This one worked great, at least with T2 when launching T2X (the only fm I have installed right now)! Thanks a lot for the quick update :)

**Comment by FenPhoenix** [comment]
Awesome! If it works with T2 then it ought to work with all the games, as the way the params are passed is the same for all. I'll close this and prepare a new release version.
