### ISSUE TITLE
fm.ini

### ISSUE THREAD

**Issue by infernuslord** [FenPhoenix/AngelLoader#58]
Is is possible for angelload to write back the fm.ini files with the contents of angeloader's DB?

**Comment by FenPhoenix** [comment]
Oh, you mean like FMSel's Tasks->Create new fm.ini option? Yeah, I guess I could do that.

**Comment by FenPhoenix** [comment]
Are you making an FM and wanting to use AngelLoader to create your fm.ini file? The slight problem here is that AngelLoader doesn't store the "Descr" (long form description) value, so you would have to write it or copy-paste it yourself into a field in the Export window. Fine if you export only once I suppose.

[Here's the window](https://fenphoenix.com/github/AngelLoader/export_fm_ini_window1.png)

**Comment by infernuslord** [comment]
Hi Fen! No the Descr field isn't necessary. But imagine you have all the FM's and all have their fm.ini, and you want to save the changes you make in AngelLoader back to those ini files.

**Comment by FenPhoenix** [comment]
Ah. Well, you wouldn't be able to rebuild your full AngelLoader data from just fm.ini files - you would lose rating, comments, finished status, game type, size, last played, date added, per-FM disabled mods...

Also, we would have to support writing these files back into zip and 7z archives in case the FM isn't installed. I'm not sure I'm comfortable with that conceptually.

**Comment by infernuslord** [comment]
For now, no support would be needed to write/back to 7z files. just unzipped missions
