### ISSUE TITLE
Option to list FMs removed from the archive (for their metadata)

### ISSUE THREAD

**Issue by maxigaz** [FenPhoenix/AngelLoader#66]
I’ve just noticed that AngelLoader keeps the metadata (comments, ratings, level completions etc.) of an FM after it was deleted from the archive. Taking this one step further, could you add an option to show these deleted FMs if there’s metadata saved for them?

I would find this useful when I wasn’t sure if I’d played a particular FM (or if I liked it) or not while browsing TTLG forums or thiefmissions.com, because this way I would be reminded just by looking at AngelLoader without having to download the FM again.

**Comment by FenPhoenix** [comment]
Absolutely, can do.
