### ISSUE TITLE
feature request: auto-uninstall before deleting installed mission

### ISSUE THREAD

**Issue by githubuser181226** [FenPhoenix/AngelLoader#69]
Mr. Fen, found this weird behavior. if a mission is installed and I delete it, I get messages the fm is missin, but it doesn't go away - it's still listed and installed.
please, consider changing this - either prevent deletion of installed missions or auto-uninstall before deleting.
cheers.

**Comment by FenPhoenix** [comment]
Oh, I see what you're saying. Yeah, the delete feature is really "delete _archive_ specifically" so I didn't think about if it was installed. I can maybe add an "Uninstall first? [ ] don't ask again" dialog.
