### ISSUE TITLE
Minor GUI bug - resizing main window "unhides" the hidden sidebar

### ISSUE THREAD

**Issue by githubuser181226** [FenPhoenix/AngelLoader#70]
Hi, Fen.

I've found a minor GUI bug:
1. Hide the sidebar - click the toggle sidebar visibility button or drag the vertical splitter to the far right.
2. Make the main window wider.
3. What happens: the sidebar slowly creeps out to view, when dragged close to the right edge the splitter doesn't snap to it.
4. What's expected: the sidebar stays hidden and the splitter should snap to the right edge when dragged close to it.

Check attatched screen capture.

Cheers.

https://user-images.githubusercontent.com/46164484/112237246-90342a00-8c42-11eb-88a3-c11b72b86620.mp4

**Comment by FenPhoenix** [comment]
Bizarre. I'll take a look at it.

**Comment by FenPhoenix** [comment]
Fixed. We're doing the collapse in a "manual" way due to how our layout has to work, so it wasn't accounting for resizing.
