### ISSUE TITLE
Access fms if they are on a network shared folder via "\\"

### ISSUE THREAD

**Issue by kek444** [FenPhoenix/AngelLoader#91]
AngelLoader can't load FMs if they are on a network shared disk which doesn't have a mapped drive letter (but is accessed via the "\\\\" syntax).

There are some practical reasons for having a local network setup such as "\\\\nas\thief\fms\" instead of "Z:\thief\fms" and since there is no technical reason why this shouldn't be supported, I believe it should be added.

**Comment by FenPhoenix** [comment]
Merged, with note to go through all code that depends on or cares about forward and backslashes in paths
