### ISSUE TITLE
[7z files] System.IO.FileNotFoundException: Could not find file 'C:\users\steamuser\Temp\AngelLoader\FMScan\<abc>.txt'

### ISSUE THREAD

**Issue by jonathanlinat** [FenPhoenix/AngelLoader#97]
Hello @FenPhoenix,

## Environment Details

- **System**: Steam Linux + Proton experimental (A Wine fork from Valve).
- **Screenshots**: 
![Environment Screenshot](https://github.com/FenPhoenix/AngelLoader/assets/14064112/fb2a89af-bb3d-440e-8d90-b47ff0f4e4d1)
![Scanned Files Screenshot](https://github.com/FenPhoenix/AngelLoader/assets/14064112/c8baf792-7be2-42bf-a008-5c646e1f75ab)
![Error Popup](https://github.com/FenPhoenix/AngelLoader/assets/14064112/c01eaf1e-ba7d-4abc-9698-e7440678d255)

## Overview

I've stored 2300+ Fan Missions in my local directory, which includes TG, TMA, and TDS missions. I converted all these files to 7z from their original Zip and Rar formats for disk space efficiency using a Python script I crafted.

While AngelLoader functions optimally overall and successfully scans and caches the files into `FMData.ini`, I encounter an error popup at the scanning's conclusion.

Here's an excerpt from my `AngelLoader_log.txt`:

```log
2023/8/25 11:29:33 ScanMany
z:\home\jonathan\.steam\steam\steamapps\common\AngelLoader\fms\tg\1_-_DOCKS.7z: Exception in FM scan
EXCEPTION:
System.IO.FileNotFoundException: Could not find file 'C:\users\steamuser\Temp\AngelLoader\FMScan\1_-_DOCKS\brief_(c).txt'.
File name: 'C:\users\steamuser\Temp\AngelLoader\FMScan\1_-_DOCKS\brief_(c).txt'
  at System.IO.FileInfo.get_Length () [0x0001d] in <69ebfd1fc56040acade074e61bd61307>:0 
  at FMScanner.Scanner.ReadAndCacheReadmeFiles (System.Collections.Generic.List`1[T] readmeDirFiles) [0x000de] in <23450f59e5f14017a2e1f12eaa0cfb94>:0 
  at FMScanner.Scanner.ScanCurrentFM (FMScanner.FMToScan fm, System.String tempPath, System.Threading.CancellationToken cancellationToken) [0x00cf5] in <23450f59e5f14017a2e1f12eaa0cfb94>:0 
  at FMScanner.Scanner.ScanMany (System.Collections.Generic.List`1[T] missions, System.String tempPath, FMScanner.ScanOptions scanOptions, System.IProgress`1[T] progress, System.Threading.CancellationToken cancellationToken) [0x0022d] in <23450f59e5f14017a2e1f12eaa0cfb94>:0 

2023/8/25 11:29:34 ScanMany
z:\home\jonathan\.steam\steam\steamapps\common\AngelLoader\fms\tma\10rooms_Cave_v1.7z: Exception in FM scan
EXCEPTION:
System.IO.FileNotFoundException: Could not find file 'C:\users\steamuser\Temp\AngelLoader\FMScan\10rooms_Cave_v1\readme.txt'.
File name: 'C:\users\steamuser\Temp\AngelLoader\FMScan\10rooms_Cave_v1\readme.txt'
  at System.IO.FileInfo.get_Length () [0x0001d] in <69ebfd1fc56040acade074e61bd61307>:0 
  at FMScanner.Scanner.ReadAndCacheReadmeFiles (System.Collections.Generic.List`1[T] readmeDirFiles) [0x000de] in <23450f59e5f14017a2e1f12eaa0cfb94>:0 
  at FMScanner.Scanner.ScanCurrentFM (FMScanner.FMToScan fm, System.String tempPath, System.Threading.CancellationToken cancellationToken) [0x00cf5] in <23450f59e5f14017a2e1f12eaa0cfb94>:0 
  at FMScanner.Scanner.ScanMany (System.Collections.Generic.List`1[T] missions, System.String tempPath, FMScanner.ScanOptions scanOptions, System.IProgress`1[T] progress, System.Threading.CancellationToken cancellationToken) [0x0022d] in <23450f59e5f14017a2e1f12eaa0cfb94>:0 

2023/8/25 11:29:35 ScanMany
z:\home\jonathan\.steam\steam\steamapps\common\AngelLoader\fms\tma\1MIL_AMNH1.0.7z: Exception in FM scan
EXCEPTION:
System.IO.FileNotFoundException: Could not find file 'C:\users\steamuser\Temp\AngelLoader\FMScan\1MIL_AMNH1.0\FMInfo.txt'.
File name: 'C:\users\steamuser\Temp\AngelLoader\FMScan\1MIL_AMNH1.0\FMInfo.txt'
  at System.IO.FileInfo.get_Length () [0x0001d] in <69ebfd1fc56040acade074e61bd61307>:0 
  at FMScanner.Scanner.ReadAndCacheReadmeFiles (System.Collections.Generic.List`1[T] readmeDirFiles) [0x000de] in <23450f59e5f14017a2e1f12eaa0cfb94>:0 
  at FMScanner.Scanner.ScanCurrentFM (FMScanner.FMToScan fm, System.String tempPath, System.Threading.CancellationToken cancellationToken) [0x00cf5] in <23450f59e5f14017a2e1f12eaa0cfb94>:0 
  at FMScanner.Scanner.ScanMany (System.Collections.Generic.List`1[T] missions, System.String tempPath, FMScanner.ScanOptions scanOptions, System.IProgress`1[T] progress, System.Threading.CancellationToken cancellationToken) [0x0022d] in <23450f59e5f14017a2e1f12eaa0cfb94>:0 
```

> **Important**
>
> This issue seems exclusive to 7z files.

## Expected Behavior

7z files should be scanned without triggering any errors. I suspect the fixed path `C:\users\steamuser\Temp\AngelLoader\FMScan\` might be causing this. A dynamic path, determined by the actual location of the local AngelLoader directory, would likely be more effective. Perhaps using the current `Data/FMCache` directory's path could be a solution?

Thank you for looking into this!

**Comment by jonathanlinat** [comment]
I'll close that issue, as it seems to be related to a bad conversion form Zip to 7z. Some of the essential files are corrupted (Check the size of the files).

## Zip vs 7z converted mission

![image](https://github.com/FenPhoenix/AngelLoader/assets/14064112/98aebda4-7dae-4a56-b682-b7a6d46adb04)

**Comment by FenPhoenix** [comment]
The 7z scan first extracts the files it needs to a temp folder, and then later in the scan it reads the files back in from disk, expecting them to be there. The extract obviously must have failed, although I would expect to see a 7z error in the log if that was the case (something like "c:\archives\the_fm.7z: fm is 7z: 7z.exe path: c:\AngelLoader\7z64\7z.exe: [error info]")

I'll look over my error handling code and see if I'm missing some situation in which an error occurs but I don't set the error flag.

**Comment by FenPhoenix** [comment]
Can you send me one of your broken 7z files? I want to test 7z.exe's error output with it.

**Comment by jonathanlinat** [comment]
@FenPhoenix Sure. Here you have:

https://ufile.io/sfkg8fph

![image](https://github.com/FenPhoenix/AngelLoader/assets/14064112/739afd0f-b354-45a9-a322-770f001b08fe)

**Comment by FenPhoenix** [comment]
Your log said "couldn't find file", so I don't think the zero size is anything to do with that. I believe there are some places in the scanner where file size is assumed to be >0 (.mis files for example), but my strategy has been to simply let those throw and fail on purpose because we'd be on a corrupt FM anyway and there'd be no point trying to scan any further.

**Comment by FenPhoenix** [comment]
Okay, I figured out what's going on. When it iterates the archive to build the files-to-extract list, it only adds readmes that are >0 length. So 0 length readmes _don't_ get extracted. But it still adds those readmes to the "file info" list, and when it goes through that list later to read the readmes in from disk, it doesn't check if the file it's about to read actually exists (it assumes it does). So a slight logic bug. I'm fixing it for the next version.

**Comment by jonathanlinat** [comment]
Awesome. Thank you, Fen.

I already converted my Python program to a Bash script, and the conversion is now working as intended. I save a lot of space, but AngelLoader is much slower with 7z files than Zip and Rar, which is, I believe, expected.

We can close the issue.

**Comment by FenPhoenix** [comment]
Yes, 7z files are much slower to scan due to their nature. They're solid archives (technically they can be non-solid, but in practice they're basically always solid). That means their data is one big compressed blob, so the scanner can't skip around and pluck out the files it needs, and it can't stream them into memory either (no api for it). Instead, it has to just decompress through the entire blob (which could be very large) until it's come across and extracted all the files it needs. This combined with the fact that 7z's LZMA format is much slower to decompress to begin with, and is also not able to be multithreaded during decompression either, makes zip files a far better fit for FMs IMO, in this age of dirt cheap storage. That's my opinion anyway, but if you're cool with making the speed/size tradeoff then go for it. But just know that I won't be able to make 7z files go any faster, I'm already extracting the minimum and calling directly out to the official native 7z.exe for max speed.

**Comment by jonathanlinat** [comment]
That's okay. And TY for the explanations. That makes sense.

I'm aiming to save space since I have to store these files on a server I pay for monthly. If I can save upwards of 30GB of data, it's worth it.

**Comment by FenPhoenix** [comment]
Ah, in that case it makes sense then.
